name: Maven Package

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: redisLib
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Verify Unit Tests and Mutants Tests
      run: mvn -B clean verify --file pom.xml
    
    - name: Build Plugin
      run: mvn -B package --file pom.xml
      
    - name: Publish to Rabbit Hole RP
      run: mvn --batch-mode deploy
      env:
          MAVEN_USERNAME: ${{ secrets.RABBITHOLE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.RABBITHOLE_TOKEN }}
